language: node_js
node_js:
  - "8"
cache: npm

jobs:
  include:
    - stage: test
      script:
        - "./node_modules/.bin/htmllint ./www/**/*.html"
        - "./node_modules/.bin/eslint ./www/**/*.js"
        - "./node_modules/.bin/eslint ./tests/**/*.js"
        - "./node_modules/.bin/stylelint ./www/**/*.css"
        - "npm test"
        - "./node_modules/.bin/jsdoc -d ./doc ./www/**/*.js"

stages:
  - name: test
 